### ISSUE TITLE
Get a list of my tasks with one command

### ISSUE THREAD

**Issue by TonyIvanova** [liyunze-coding/Chat-Task-Tic-Overlay#5]
Would be nice to be able to get the list of my not completed tasks with one command. 
Case: 
I have a list of tasks: 
1. a
2. b

I marked 1 and 2 as done. I join next stream. And add new tasks. For example 
1. c 
2. d 

Now the tasks are actually added as 
1. a 
2. b
3. c
4. d

and if I do !done 1 it checks off task a, but I would expect it to check out the task c, since a and b are done. 

Having a command that gives me the list of my task would make it easier navigating it.

**Comment by liyunze-coding** [comment]
is this referring to the multi-task widget? You can check the incomplete tasks using: `!check` or `!mytasks` for the index of the task, or you can also do `!done c` if you remember the task name but not the index.

Let me know if you found this helpful or not!

**Comment by TonyIvanova** [comment]
Thanks! That worked for me, appreciate the answer.
